<?php
$file = '../data/anomaly_results.csv';
$data = [];

// Read the CSV data generated by your Python AI
if (file_exists($file)) {
    if (($handle = fopen($file, "r")) !== FALSE) {
        $headers = fgetcsv($handle, 1000, ",");
        while (($data_row = fgetcsv($handle, 1000, ",")) !== FALSE) {
            $data[] = array_combine($headers, $data_row);
        }
        fclose($handle);
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>AI-Sentinel Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        body { background-color: #f8f9fa; }
        .threat-row { background-color: #f8d7da !important; color: #721c24; font-weight: bold; }
        .safe-row { background-color: #d4edda !important; color: #155724; }
    </style>
</head>
<body>
<div class="container mt-5">
    <h2 class="mb-4">🛡️ AI-Sentinel: Network Security Monitor</h2>
    
    <div class="card shadow">
        <div class="card-header bg-dark text-white">Live Traffic Analysis</div>
        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Time</th>
                        <th>Source IP</th>
                        <th>Destination IP</th>
                        <th>Protocol</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data as $row): ?>
                        <?php $is_anomaly = ($row['anomaly_score'] == -1); ?>
                        <tr class="<?= $is_anomaly ? 'threat-row' : 'safe-row' ?>">
                            <td><?= $row['Time'] ?></td>
                            <td><?= $row['Source'] ?></td>
                            <td><?= $row['Destination'] ?></td>
                            <td><?= $row['Protocol'] ?></td>
                            <td><?= $is_anomaly ? '🚨 THREAT DETECTED' : '✅ SECURE' ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>